sudo: false
language: php
php:
  - 7.2
  - 7.3
  - 7.4snapshot

cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - mysql
  - postgresql

addons:
  apt:
    packages:
    - libxml2-utils

env:
  global:
    - CORE_BRANCH=stable19
    - PHP_COVERAGE=FALSE
  matrix:
    # Nextcloud 19+
    - CORE_TYPE=nextcloud DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

matrix:
  fast_finish: true
  include:
    # Older Nextcloud versions
    - php: 7.3
      env: CORE_TYPE=nextcloud CORE_BRANCH=stable18 DB=sqlite
    - php: 7.2
      env: CORE_TYPE=nextcloud CORE_BRANCH=stable17 DB=sqlite

    # Other Databases
    - php: 7.3
      env: CORE_TYPE=nextcloud CORE_BRANCH=stable19 DB=mysql
    - php: 7.3
      env: CORE_TYPE=nextcloud CORE_BRANCH=stable19 DB=pgsql

before_install:
  # XDebug is only needed if we report coverage -> speeds up other builds
  - if [[ "$PHP_COVERAGE" = "FALSE" ]]; then phpenv config-rm xdebug.ini; fi

install:
  - . ./tests/scripts/core-download.sh
  - . ${BUILD_APP_MODULE_DIR}/tests/scripts/core-database.sh
  - . ${BUILD_APP_MODULE_DIR}/tests/scripts/core-setup.sh

script:
  # Check info.xml schema validity
  - . ${BUILD_APP_MODULE_DIR}/tests/scripts/lint-appinfo.sh

  # Check PHP syntax errors
  - . ${BUILD_APP_MODULE_DIR}/tests/scripts/lint-php.sh

  # Run app code checker but do not fail, as we have to use private API for now
  - . ${BUILD_APP_MODULE_DIR}/tests/scripts/app-check-code.sh || true

  # Run PHP tests
  - . ${BUILD_APP_MODULE_DIR}/tests/scripts/phpunit.sh
