sudo: false
language: php
php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - mysql
  - postgresql

addons:
  apt:
    packages:
    - libxml2-utils

env:
  global:
    - CORE_TYPE=nextcloud
    - CORE_BRANCH=master
    - APP_NAME=notifications
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

matrix:
  include:
    - php: 7.3
      env: DB=mysql
    - php: 7.3
      env: DB=pgsql
    - php: 7.2
      env: DB=sqlite CORE_BRANCH=stable19
    - php: 7.2
      env: DB=sqlite CORE_BRANCH=stable18
    - php: 7.2
      env: DB=sqlite CORE_BRANCH=stable17
    - php: 7.3
      env: DB=sqlite CORE_BRANCH=master CORE_TYPE=owncloud
  fast_finish: true

before_install:
  # XDebug is only needed if we report coverage -> speeds up other builds
  - if [[ "$PHP_COVERAGE" = "FALSE" ]]; then phpenv config-rm xdebug.ini; fi

install:
  - . ./tests/scripts/core-download.sh
  - . ${BUILD_APP_MODULE_DIR}/tests/scripts/core-database.sh
  - . ${BUILD_APP_MODULE_DIR}/tests/scripts/core-setup.sh

script:
  # Run app code checker but do not fail, as we have to use private API for now
  - . ${BUILD_APP_MODULE_DIR}/tests/scripts/app-check-code.sh || true

  # Run PHP tests
  - . ${BUILD_APP_MODULE_DIR}/tests/scripts/phpunit.sh
