sudo: false
language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - mysql
  - postgresql

addons:
  apt:
    packages:
    - php5-pgsql
    - libxml2-utils

env:
  global:
    - PHP_COVERAGE=FALSE
  matrix:
    - CORE_TYPE=nextcloud CORE_BRANCH=master    DB=sqlite
    - CORE_TYPE=nextcloud CORE_BRANCH=stable12  DB=sqlite
    - CORE_TYPE=nextcloud CORE_BRANCH=stable11  DB=sqlite

    - CORE_TYPE=nextcloud CORE_BRANCH=master    DB=mysql
    - CORE_TYPE=nextcloud CORE_BRANCH=stable12  DB=mysql
    - CORE_TYPE=nextcloud CORE_BRANCH=stable11  DB=mysql

    - CORE_TYPE=nextcloud CORE_BRANCH=master    DB=pgsql
    - CORE_TYPE=nextcloud CORE_BRANCH=stable12  DB=pgsql
    - CORE_TYPE=nextcloud CORE_BRANCH=stable11  DB=pgsql

    - CORE_TYPE=owncloud  CORE_BRANCH=master    DB=sqlite
    - CORE_TYPE=owncloud  CORE_BRANCH=stable10  DB=sqlite

    - CORE_TYPE=owncloud  CORE_BRANCH=master    DB=mysql
    - CORE_TYPE=owncloud  CORE_BRANCH=stable10  DB=mysql

    - CORE_TYPE=owncloud  CORE_BRANCH=master    DB=pgsql
    - CORE_TYPE=owncloud  CORE_BRANCH=stable10  DB=pgsql

matrix:
  fast_finish: true
  exclude:
    # Nextcloud 11/12 are not compatible with PHP 7.2
    - php: 7.2
      env: CORE_TYPE=nextcloud CORE_BRANCH=stable11  DB=mysql
    - php: 7.2
      env: CORE_TYPE=nextcloud CORE_BRANCH=stable12  DB=mysql
    - php: 7.2
      env: CORE_TYPE=nextcloud CORE_BRANCH=stable11  DB=sqlite
    - php: 7.2
      env: CORE_TYPE=nextcloud CORE_BRANCH=stable12  DB=sqlite
    - php: 7.2
      env: CORE_TYPE=nextcloud CORE_BRANCH=stable11  DB=pgsql
    - php: 7.2
      env: CORE_TYPE=nextcloud CORE_BRANCH=stable12  DB=pgsql

before_install:
  # XDebug is only needed if we report coverage -> speeds up other builds
  - if [[ "$PHP_COVERAGE" = "FALSE" ]]; then phpenv config-rm xdebug.ini; fi

install:
  - . ./tests/scripts/core-download.sh
  - . ${BUILD_APP_MODULE_DIR}/tests/scripts/core-database.sh
  - . ${BUILD_APP_MODULE_DIR}/tests/scripts/core-setup.sh

script:
  # Check info.xml schema validity
  - . ${BUILD_APP_MODULE_DIR}/tests/scripts/lint-appinfo.sh

  # Check PHP syntax errors
  - . ${BUILD_APP_MODULE_DIR}/tests/scripts/lint-php.sh

  # Run app code checker but do not fail, as we have to use private API for now
  - . ${BUILD_APP_MODULE_DIR}/tests/scripts/app-check-code.sh || true

  # Run PHP tests
  - . ${BUILD_APP_MODULE_DIR}/tests/scripts/phpunit.sh
